dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install black flake8
  - pip install pytest-cov codecov
  - pip install .
script:
  - black --check demo
  - flake8 demo
  - pytest --cov=./
after_success:
  - codecov
jobs:
  include:
    - stage: deploy
      python: "3.6"
      install:
        - pip install sphinx sphinx-rtd-theme
      script:
        - sphinx-apidoc -f -o docs/_apidoc demo
        - sphinx-build docs docs/_build
        - sphinx-build docs docs/_build
      deploy:
        provider: pages
        local-dir: docs/_build
        target-branch: gh-pages
        github-token: $GITHUB_TOKEN
        skip-cleanup: true
        keep-history: true
        on:
          branch: master
